# Generated by Django 5.0.6 on 2024-06-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_lastname', models.CharField(max_length=255, verbose_name='Фамилия покупателя')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('buyer_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество покупателя')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к заказу')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Магазин'), ('CR', 'Доставка курьером'), ('PP', 'Пункт выдачи')], default='SH', max_length=2, verbose_name='Способ доставки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название компании')),
                ('agent_lastname', models.CharField(max_length=255, verbose_name='Фамилия представителя')),
                ('agent_name', models.CharField(max_length=255, verbose_name='Имя представителя')),
                ('agent_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество представителя')),
                ('agent_telephone', models.CharField(max_length=16, verbose_name='Телефон представителя')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Логическое удаление')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Pos_parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('parametr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.parametr', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография товара')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Логическое удаление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория')),
                ('parametr', models.ManyToManyField(through='shop.Pos_parametr', to='shop.parametr', verbose_name='Характеристики товара')),
                ('tag', models.ManyToManyField(blank=True, to='shop.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Pos_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставок',
            },
        ),
        migrations.AddField(
            model_name='pos_parametr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='shop.Pos_order', to='shop.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_supply', models.DateTimeField(verbose_name='Дата поставки')),
                ('product', models.ManyToManyField(through='shop.Pos_supply', to='shop.product', verbose_name='Товар')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.AddField(
            model_name='pos_supply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.supply', verbose_name='Поставка'),
        ),
    ]
